### ISSUE TITLE
It's possible to configure skoruba only with docker images using docker-compose?

### ISSUE THREAD

**Issue by mMarcos208** [skoruba/IdentityServer4.Admin#569]
I have docker-compose with Identity Server and other applications.
I would like to add skoruba images from docker hub in my docker compose.

How can I modify the port of `identityserver4-sts-identity:rc1` and to add admin login and password for admin UI?

What I need to modify in my configurations?

Code:
```
version: "3"
services:

  identityserver:
    container_name: identityserver
    image: "agrohub-server"
    environment:
      connectionStringServer: "Server=host.docker.internal,1433;Database=AgroHub_IDS;Trusted_Connection=False;User=sa;Password=Password1234;MultipleActiveResultSets=True"
      connectionStringIdentity: "Server=host.docker.internal,1433;Database=AgroHub_UUID;Trusted_Connection=False;User=sa;Password=Password1234;MultipleActiveResultSets=True"
    ports:
      - "5000:5000"
    depends_on:
      - banco
 
  adminui:
    container_name: adminui
    image: "skoruba/identityserver4-admin:rc1"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__ConfigurationDbConnection=Server=host.docker.internal,1433;Database=AgroHub_IDS;Trusted_Connection=False;User=sa;Password=Password1234;MultipleActiveResultSets=True"
      - "ConnectionStrings__PersistedGrantDbConnection=Server=host.docker.internal,1433;Database=AgroHub_IDS;Trusted_Connection=False;User=sa;Password=Password1234;MultipleActiveResultSets=True"
      - "ConnectionStrings__IdentityDbConnection=Server=host.docker.internal,1433;Database=AgroHub_IDS;Trusted_Connection=False;User=sa;Password=Password1234;MultipleActiveResultSets=True"
      - "ConnectionStrings__AdminLogDbConnection=Server=host.docker.internal,1433;Database=AgroHub_IDS;Trusted_Connection=False;User=sa;Password=Password1234;MultipleActiveResultSets=True"
      - "ConnectionStrings__AdminAuditLogDbConnection=Server=host.docker.internal,1433;Database=AgroHub_IDS;Trusted_Connection=False;User=sa;Password=Password1234;MultipleActiveResultSets=True"
      - "AdminConfiguration__IdentityAdminBaseUrl=http://127.0.0.1.xip.io:9000"
      - "AdminConfiguration__IdentityAdminRedirectUri=http://127.0.0.1.xip.io:9000/signin-oidc"
      - "AdminConfiguration__IdentityServerBaseUrl=http://127.0.0.1.xip.io"
      - "AdminConfiguration__RequireHttpsMetadata=false"
      - "IdentityServerData__Clients__0__ClientUri=http://127.0.0.1.xip.io:9000"
      - "IdentityServerData__Clients__0__RedirectUris__0=http://127.0.0.1.xip.io:9000/signin-oidc"
      - "IdentityServerData__Clients__0__FrontChannelLogoutUri=http://127.0.0.1.xip.io:9000/signin-oidc"
      - "IdentityServerData__Clients__0__PostLogoutRedirectUris__0=http://127.0.0.1.xip.io:9000/signout-callback-oidc"
      - "IdentityServerData__Clients__0__AllowedCorsOrigins__0=http://127.0.0.1.xip.io:9000"
      - "IdentityServerData__Clients__1__RedirectUris__0=http://127.0.0.1.xip.io:9001/swagger/oauth2-redirect.html"
      - "Serilog__WriteTo__1__Args__connectionString=Server=host.docker.internal,1433;Database=AgroHub_IDS;Trusted_Connection=False;User=sa;Password=Password1234;MultipleActiveResultSets=True"
    ports:
      - "9000:80"
    depends_on:
      - banco
  
  adminapi:
    container_name: adminapi
    image: "skoruba/identityserver4-admin-api:rc1"
    environment:
      - "AdminApiConfiguration__RequireHttpsMetadata=false"
      - "AdminApiConfiguration__ApiBaseUrl=http://127.0.0.1.xip.io:9001"
      - "AdminApiConfiguration__IdentityServerBaseUrl=http://127.0.0.1.xip.io:9000"
      - "ConnectionStrings__ConfigurationDbConnection=Server=host.docker.internal,1433;Database=AgroHub_IDS;Trusted_Connection=False;User=sa;Password=Password1234;MultipleActiveResultSets=True"
      - "ConnectionStrings__PersistedGrantDbConnection=Server=host.docker.internal,1433;Database=AgroHub_IDS;Trusted_Connection=False;User=sa;Password=Password1234;MultipleActiveResultSets=True"
      - "ConnectionStrings__IdentityDbConnection=Server=host.docker.internal,1433;Database=AgroHub_IDS;Trusted_Connection=False;User=sa;Password=Password1234;MultipleActiveResultSets=True"
      - "ConnectionStrings__AdminLogDbConnection=Server=host.docker.internal,1433;Database=AgroHub_IDS;Trusted_Connection=False;User=sa;Password=Password1234;MultipleActiveResultSets=True"
      - "ConnectionStrings__AdminAuditLogDbConnection=Server=host.docker.internal,1433;Database=AgroHub_IDS;Trusted_Connection=False;User=sa;Password=Password1234;MultipleActiveResultSets=True"
    ports:
      - "9001:80"
    depends_on:
      - banco

  sts:
    container_name: sts
    image: "skoruba/identityserver4-sts-identity:rc1"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__ConfigurationDbConnection=Server=host.docker.internal,1433;Database=AgroHub_IDS;Trusted_Connection=False;User=sa;Password=Password1234;MultipleActiveResultSets=True"
      - "ConnectionStrings__PersistedGrantDbConnection=Server=host.docker.internal,1433;Database=AgroHub_IDS;Trusted_Connection=False;User=sa;Password=Password1234;MultipleActiveResultSets=True"
      - "ConnectionStrings__IdentityDbConnection=Server=host.docker.internal,1433;Database=AgroHub_IDS;Trusted_Connection=False;User=sa;Password=Password1234;MultipleActiveResultSets=True"
      - "AdminConfiguration__IdentityAdminBaseUrl=http://127.0.0.1.xip.io:9000"
    ports:
      - "81:80"
    depends_on:
      - banco
    networks:
      default:
        aliases:
          - 127.0.0.1.xip.io

  banco:
    container_name: banco
    image: "mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password1234"
    ports:
      - "1433:1433"

```
