### ISSUE TITLE
Admin panel oidc callback url not work when running with docker image

### ISSUE THREAD

**Issue by inamvar** [skoruba/IdentityServer4.Admin#579]
I started docker containers but admin oidc callback url not working. here is my docker-compose file.

``` yml
version: '3.4'

services:
  ids.admin:
    image: skoruba/identityserver4-admin:rc1
    container_name: ids-admin
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - "ConnectionStrings__ConfigurationDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__PersistedGrantDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__IdentityDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__AdminLogDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__AdminAuditLogDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "AdminConfiguration__IdentityAdminBaseUrl=https://admin.accounts.dariksoft.com"
      - "AdminConfiguration__IdentityAdminRedirectUri=https://admin.accounts.dariksoft.com/signin-oidc"
      - "AdminConfiguration__IdentityServerBaseUrl=https://accounts.dariksoft.com"
      - "AdminConfiguration__RequireHttpsMetadata=true"
      - "IdentityServerData__Clients__0__ClientUri=https://admin.accounts.dariksoft.com"
      - "IdentityServerData__Clients__0__RedirectUris__0=https://admin.accounts.dariksoft.com/signin-oidc"
      - "IdentityServerData__Clients__0__FrontChannelLogoutUri=https://admin.accounts.dariksoft.com/signin-oidc"
      - "IdentityServerData__Clients__0__PostLogoutRedirectUris__0=https://admin.accounts.dariksoft.com/signout-callback-oidc"
      - "IdentityServerData__Clients__0__AllowedCorsOrigins__0=https://admin.accounts.dariksoft.com"
      - "IdentityServerData__Clients__1__RedirectUris__0=https://api.accounts.dariksoft.com/swagger/oauth2-redirect.html"
      - "Serilog__WriteTo__1__Args__connectionString=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
    command: dotnet Skoruba.IdentityServer4.Admin.dll /seed
    depends_on:
      - db
      - ids.sts.identity
    volumes:
      - "/var/ids/shared/serilog.json:/app/serilog.json"
      - "/var/ids/shared/identitydata.json:/app/identitydata.json"
      - "/var/ids/shared/identityserverdata.json:/app/identityserverdata.json"
    ports:
      - 9000:80
    volumes:
      - /var/ids/secrets:/root/.microsoft/usersecrets:ro

  ids.admin.api:
    image: skoruba/identityserver4-admin-api:rc1
    container_name: ids-api
    environment:
      - "AdminApiConfiguration__RequireHttpsMetadata=false"
      - "AdminApiConfiguration__ApiBaseUrl=https://api.accounts.dariksoft.com"
      - "AdminApiConfiguration__IdentityServerBaseUrl=https://accounts.dariksoft.com"
      - "ConnectionStrings__ConfigurationDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__PersistedGrantDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__IdentityDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__AdminLogDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__AdminAuditLogDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
    ports:
      - 9001:80
    volumes:
      - /var/ids/secrets:/root/.microsoft/usersecrets:ro

  ids.sts.identity:
    image: skoruba/identityserver4-sts-identity:rc1
    container_name: ids-sts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__ConfigurationDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__PersistedGrantDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__IdentityDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "AdminConfiguration__IdentityAdminBaseUrl=https://admin.accounts.dariksoft.com"
    depends_on:
      - db
    ports:
      - 5000:80
    volumes:
      - /var/ids/secrets:/root/.microsoft/usersecrets:ro
    networks:
      default:
        aliases:
          - accounts.dariksoft.com
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - 1433:1433
    container_name: ids-db
    environment:
      SA_PASSWORD: "${DB_PASSWORD:-Password_123}"
      ACCEPT_EULA: "Y"
    volumes:
      - dbdata:/var/opt/mssql

volumes:
  dbdata:
    driver: local


networks:
  default:
    driver: bridge
```
